spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchange?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: 192.168.40.30
    port: 6379
    timeout: 6000ms
    password: 12345678
server:
  port: 8090

